spars:
  sampler: "uniform" # one of "halton", "uniform"
  denseDelta: 1
  sparseDelta: 10
  stretchFactor: 1.01
  maxFailures: 500
  maxIter: 500000
  maxTime: 1
connection:
  maxNeighbors: 6
  maxRadius: 0.6
