name: Python package

on:
  schedule:
    - cron:  '0 0 * * 0'  # 0:00 on sundays
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{github.workspace}}
      SCENARIO_STORAGE_PATH: ${{github.workspace}}/.scenario_cache
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r planner/mapf_implementations/requirements.txt
        pip install -r sim/decentralized/requirements.txt
        pip install -r requirements-torch_cpu.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
    # - name: Build cobra
    #   run: |
    #     cd planner/cobra/external
    #     ./make_cobra.sh
    - name: Build ecbs, cbs_roadmap and cbs_ta
      run: |
        sudo apt install -y cmake libboost1.74-dev libboost-program-options1.74-dev libboost-regex1.74-dev libyaml-cpp-dev
        rm -rf planner/mapf_implementations/libMultiRobotPlanning/build
        mkdir planner/mapf_implementations/libMultiRobotPlanning/build
        cd planner/mapf_implementations/libMultiRobotPlanning/build
        cmake ..
        make ecbs cbs_roadmap cbs_ta
    - name: Ecbs deps
      run: |
        sudo apt install libyaml-cpp0.7
    - name: Build astar_boost
      run: |
        sudo apt install -y cmake libboost-python1.74-dev libboost-graph1.74-dev libboost-random1.74-dev
        cd planner/astar_boost
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Build ompl
      run: |
        sudo apt install -y cmake libboost1.74-dev libboost-program-options1.74-dev libboost-filesystem1.74-dev libboost-serialization1.74-dev libboost-python1.74-dev libopencv-dev libompl-dev
        cd roadmaps/ompl
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Test with pytest
      run: |
        pytest -vs
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Pre-commit
      uses: pre-commit/action@v3.0.1
