name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r planner/mapf_implementations/requirements.txt
        pip install -r sim/decentralized/requirements.txt
        pip install -r learn/pytorch/requirements.txt -f https://download.pytorch.org/whl/torch_stable.html -f https://pytorch-geometric.com/whl/torch-1.9.0+cpu.html
    # - name: Build cobra
    #   run: |
    #     cd planner/cobra/external
    #     ./make_cobra.sh
    - name: Build ecbs
      run: |
        sudo apt install -y cmake libboost-dev libboost-program-options-dev libboost-regex-dev libyaml-cpp-dev
        mkdir planner/mapf_implementations/libMultiRobotPlanning/build
        cd planner/mapf_implementations/libMultiRobotPlanning/build
        cmake ..
        make ecbs
    - name: Lint with pycodestyle
      run: |
        pycodestyle .
    - name: Type checking with mypy
      run: |
        mypy scenarios sim/decentralized/
    - name: Test with pytest
      run: |
        pytest -rP