name: Python package

on:
  schedule:
    - cron:  '0 0 * * 0'  # 0:00 on sundays
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r planner/mapf_implementations/requirements.txt
        pip install -r sim/decentralized/requirements.txt
        pip install -r requirements-torch_cpu.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
    # - name: Build cobra
    #   run: |
    #     cd planner/cobra/external
    #     ./make_cobra.sh
    - name: Build ecbs and cbs_roadmap
      run: |
        sudo apt install -y cmake libboost1.71-dev libboost-program-options1.71-dev libboost-regex1.71-dev libyaml-cpp-dev
        rm -rf planner/mapf_implementations/libMultiRobotPlanning/build
        mkdir planner/mapf_implementations/libMultiRobotPlanning/build
        cd planner/mapf_implementations/libMultiRobotPlanning/build
        cmake ..
        make ecbs cbs_roadmap
    - name: Ecbs deps
      run: |
        sudo apt install libyaml-cpp0.6
    - name: Build astar_boost
      run: |
        sudo apt install -y cmake libboost-python1.71-dev libboost-graph1.71-dev libboost-random1.71-dev
        cd planner/astar_boost
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Test with pytest
      run: |
        pytest -rP
  mypy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r planner/mapf_implementations/requirements.txt
        pip install -r sim/decentralized/requirements.txt
        pip install -r requirements-torch_cpu.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
    - name: Type checking with mypy
      run: |
        mypy
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
