on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker pull ct2034/miriam
          docker build -t ct2034/miriam .
      - name: Push docker image
        run: |
          docker push ct2034/miriam
      - name: Run docker image
        run: |
          docker run -m 8G --memory-swap=8G ct2034/miriam